### ISSUE TITLE
1.21.1 Paper support

### ISSUE THREAD

**Issue by mjl1010** [NewAgeCZ/CommandHook#10]
I don't know if it fails in Spigot, but in Paper 1.21.1 I get the following error:

```
[09:14:18 ERROR]: Could not pass event ServerCommandEvent to CommandHook v3.1.0
java.lang.NoSuchMethodError: 'void net.minecraft.commands.arguments.selector.EntitySelectorParser.<init>(com.mojang.brigadier.StringReader)'
        at CommandHook.jar/org.bitbucket._newage.commandhook.mapping.MojangMapping.getArgumentParser(MojangMapping.java:62) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.mapping.MojangMapping.getEntitiesFromSelector(MojangMapping.java:28) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.CommandBlockListener.onCommandBlockDispatch(CommandBlockListener.java:39) ~[CommandHook.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor313.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-13-7c9240f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.Commands.dispatchServerCommand(Commands.java:302) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.world.level.BaseCommandBlock.performCommand(BaseCommandBlock.java:139) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.world.level.block.CommandBlock.execute(CommandBlock.java:132) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.world.level.block.CommandBlock.tick(CommandBlock.java:119) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1222) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1192) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:192) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:89) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Thank you :)

**Comment by Internetpilot** [comment]
I can confirm that I'm getting the same error on PaperMC v1.21.1 as well. Thank you!

**Comment by rRampelnik** [comment]
Yea! I have same trouble with Purpur 1.21

**Comment by colaman90** [comment]
I get the same error on Purpur 1.21.1
Any news on it ? :) 
kind regards

**Comment by Gero1909** [comment]
I have the same error. 
Im looking forward to hearing news from you.

Best regards,

G.

**Comment by Waterman1001** [comment]
I have the same problem indeed!

**Comment by snurre0** [comment]
Just wanted to chime in to say that I'm experiencing basically the same exact error in the latest 1.21.3 paper experimental version.
Probably the same issue, here is the error from my log:

```
[08:33:33] [Server thread/ERROR]: Could not pass event ServerCommandEvent to CommandHook v3.1.0
java.lang.NoSuchMethodError: 'void net.minecraft.commands.arguments.selector.EntitySelectorParser.<init>(com.mojang.brigadier.StringReader)'
        at CommandHook-3.1.0.jar/org.bitbucket._newage.commandhook.mapping.MojangMapping.getArgumentParser(MojangMapping.java:62) ~[CommandHook-3.1.0.jar:?]
        at CommandHook-3.1.0.jar/org.bitbucket._newage.commandhook.mapping.MojangMapping.getEntitiesFromSelector(MojangMapping.java:28) ~[CommandHook-3.1.0.jar:?]
        at CommandHook-3.1.0.jar/org.bitbucket._newage.commandhook.CommandBlockListener.onCommandBlockDispatch(CommandBlockListener.java:39) ~[CommandHook-3.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor312.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.Commands.dispatchServerCommand(Commands.java:307) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.world.level.BaseCommandBlock.performCommand(BaseCommandBlock.java:139) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.world.level.block.CommandBlock.execute(CommandBlock.java:143) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.world.level.block.CommandBlock.tick(CommandBlock.java:120) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1277) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1251) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:190) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:87) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:752) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1873) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1662) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1328) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by JohnS333** [comment]
CommandHookPaper works in 1.21.1 even though it says 1.21.3 minimum! https://hangar.papermc.io/YanisBft/CommandHookPaper
