### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by grdmnt** [NewAgeCZ/CommandHook#2]
Is this going to be updated for 1.19? Thanks!

**Comment by ikuria** [comment]
yepp, please update <3

**Comment by candy999** [comment]
[13:27:14 INFO]: [org.bitbucket._newage.commandhook.CommandHook] NMS package found: v1_19_R1
[13:27:14 WARN]: [org.bitbucket._newage.commandhook.mapping.NmsMappingSelector] Mapping for v1_19_R1 not found! Either the plugin is outdated or has not been updated yet!
[13:27:14 INFO]: [org.bitbucket._newage.commandhook.mapping.NmsMappingSelector] Falling back to legacy mode
[13:27:20 ERROR]: Could not pass event ServerCommandEvent to CommandHook v2.1.2
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
        at org.bitbucket._newage.commandhook.legacy.mapping.RefUtil.getEntityUUID(RefUtil.java:148) ~[CommandHook.jar:?]
        at org.bitbucket._newage.commandhook.legacy.mapping.RefUtil.lambda$reflectedParse$0(RefUtil.java:96) ~[CommandHook.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$SubList$2.forEachRemaining(ArrayList.java:1481) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at org.bitbucket._newage.commandhook.legacy.mapping.RefUtil.reflectedParse(RefUtil.java:98) ~[CommandHook.jar:?]
        at org.bitbucket._newage.commandhook.legacy.mapping.RefUtil.parse(RefUtil.java:79) ~[CommandHook.jar:?]
        at org.bitbucket._newage.commandhook.legacy.mapping.LegacyMapping.getEntitiesFromSelector(LegacyMapping.java:21) ~[CommandHook.jar:?]
        at org.bitbucket._newage.commandhook.CommandBlockListener.onCommandBlockDispatch(CommandBlockListener.java:39) ~[CommandHook.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor450.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1668]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.Commands.dispatchServerCommand(Commands.java:244) ~[?:?]
        at net.minecraft.world.level.BaseCommandBlock.performCommand(BaseCommandBlock.java:133) ~[?:?]
        at net.minecraft.world.level.block.CommandBlock.execute(CommandBlock.java:121) ~[?:?]
        at net.minecraft.world.level.block.CommandBlock.tick(CommandBlock.java:108) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1032) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1183) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:655) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1579) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by grdmnt** [comment]
I believe we have to update mappings, but I honestly don't know how to do MC plugins. If I can help with anything though, I'm down.

**Comment by NewAgeCZ** [comment]
I added the mappings required for 1.19, see 3bad3f46d7aea0ff25b7b69389d235313b912fe2
New version is available on Spigot
