### ISSUE TITLE
1.19.3 Support

### ISSUE THREAD

**Issue by CorvetteCole** [NewAgeCZ/CommandHook#5]
Does not seem to be set up for 1.19.3 yet, although still works as far as I can tell. Log output:

<pre>[23:45:17 INFO]: [CommandHook] Enabling CommandHook v2.2.0
[23:45:17 INFO]: [org.bitbucket._newage.commandhook.CommandHook] NMS package found: v1_19_R2
<span style="color:#E9AD0C"><b>[23:45:17 WARN]: [org.bitbucket._newage.commandhook.mapping.NmsMappingSelector] Mapping for v1_19_R2 not found! Either the plugin is outdated or has not been updated yet!</b></span>
[23:45:17 INFO]: [org.bitbucket._newage.commandhook.mapping.NmsMappingSelector] Falling back to legacy mode
</pre>

**Comment by CorvetteCole** [comment]
Nope, there is at least one actual issue:
<pre><span style="color:#F66151"><b>[23:57:49 ERROR]: Could not pass event ServerCommandEvent to CommandHook v2.2.0</b></span>
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader &apos;bootstrap&apos;)
        at org.bitbucket._newage.commandhook.legacy.mapping.RefUtil.getEntityUUID(RefUtil.java:148) ~[CommandHook.jar:?]
        at org.bitbucket._newage.commandhook.legacy.mapping.RefUtil.lambda$reflectedParse$0(RefUtil.java:96) ~[CommandHook.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at org.bitbucket._newage.commandhook.legacy.mapping.RefUtil.reflectedParse(RefUtil.java:98) ~[CommandHook.jar:?]
        at org.bitbucket._newage.commandhook.legacy.mapping.RefUtil.parse(RefUtil.java:79) ~[CommandHook.jar:?]
        at org.bitbucket._newage.commandhook.legacy.mapping.LegacyMapping.getEntitiesFromSelector(LegacyMapping.java:21) ~[CommandHook.jar:?]
        at org.bitbucket._newage.commandhook.CommandBlockListener.onCommandBlockDispatch(CommandBlockListener.java:39) ~[CommandHook.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1870]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.Commands.dispatchServerCommand(Commands.java:263) ~[?:?]
        at net.minecraft.world.level.BaseCommandBlock.performCommand(BaseCommandBlock.java:133) ~[?:?]
        at net.minecraft.world.level.block.CommandBlock.execute(CommandBlock.java:121) ~[?:?]
        at net.minecraft.world.level.block.CommandBlock.tick(CommandBlock.java:98) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1041) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1244) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:696) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[purpur-1.19.3.jar:git-Purpur-1870]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1870]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1870]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1870]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1870]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
</pre>

**Comment by NewAgeCZ** [comment]
Resolved by c19f4374d7af7d8d8f411b8ecc561c09ae54c60e
Thanks for the notice.
