### ISSUE TITLE
1.20.6 Support

### ISSUE THREAD

**Issue by RapidGravy** [NewAgeCZ/CommandHook#8]
Plugin needs to be updated to work with 1.20.6

```
[19:43:51 ERROR]: [org.bitbucket._newage.commandhook.legacy.V1_18] Error preparing reflection mapping for version 1.20.6java.lang.ClassNotFoundException: org.bukkit.craftbukkit.1.20.6.CraftWorld
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.1.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at CommandHook.jar/org.bitbucket._newage.commandhook.legacy.V1_18.<init>(V1_18.java:23) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.legacy.mapping.ReflectionMappingSelector.fromNmsVersion(ReflectionMappingSelector.java:33) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.legacy.mapping.LegacyMapping.<init>(LegacyMapping.java:15) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.mapping.NmsMappingSelector.fromMinecraftVersion(NmsMappingSelector.java:185) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.CommandHook.getMappingFromBukkitVersion(CommandHook.java:43) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.CommandHook.onEnable(CommandHook.java:22) ~[CommandHook.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:444) ~[purpur-1.20.6.jar:git-Purpur-2192]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:358) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:43:51 ERROR]: Error occurred while enabling CommandHook v2.4.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null
        at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:77) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.1.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at CommandHook.jar/org.bitbucket._newage.commandhook.legacy.mapping.RefUtil.<init>(RefUtil.java:67) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.legacy.mapping.LegacyMapping.<init>(LegacyMapping.java:16) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.mapping.NmsMappingSelector.fromMinecraftVersion(NmsMappingSelector.java:185) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.CommandHook.getMappingFromBukkitVersion(CommandHook.java:43) ~[CommandHook.jar:?]
        at CommandHook.jar/org.bitbucket._newage.commandhook.CommandHook.onEnable(CommandHook.java:22) ~[CommandHook.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:444) ~[purpur-1.20.6.jar:git-Purpur-2192]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:358) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2192]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Kryniowesegryderiusz** [comment]
It would be nice to know if there are plans to migrate to new mappings <3

**Comment by Greymagic27** [comment]
I messaged the creator about this on spigot and discord but got no reply to both.

**Comment by Dalethium** [comment]
https://github.com/WeNeedCoffee/CommandHook/releases/tag/1.20.6
I built this version for 1.20.6. It should work. Enjoy. I offer no guarantees, Please do not expect me to maintain this further, this was just done as a favour for a friend.

**Comment by NewAgeCZ** [comment]
Hi all,
firstly, thank you @Dalethium for your quick port.

It seems like Paper ditched NMS packages, which is cool, because the plugin might be upwards compatible without new releases every Minecraft version.
Spigot kept NMS, that means it needs separate modules for it to work and they might be required for the plugin to be kept at Spigot's site.

I am really busy with my personal life/work, also not actively playing or maintaining any MC server since 2019, so this is more of a burden to me. However, I will try to push new release this or next weekend, because it seems like the plugin is still used by a few, no guaranties though...

**Comment by NewAgeCZ** [comment]
New version has been released on Spigot's site. Let me know if everything works okay for you all :)
